# Generated by Django 4.2.7 on 2025-10-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenantprofile_landlord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='government_id',
            new_name='national_id',
        ),
    ]
