# Generated by Django 4.2.7 on 2025-10-26 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_government_id_customuser_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='tenant',
            field=models.OneToOneField(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tenantprofile',
            unique_together={('tenant', 'landlord')},
        ),
    ]
