# Generated by Django 4.2.7 on 2025-10-28 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_groups_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('already_living_in_property', models.BooleanField(default=False, help_text="True if tenant already lives in this landlord's property")),
                ('deposit_required', models.BooleanField(default=True, help_text='Whether deposit payment is required')),
                ('deposit_paid', models.BooleanField(default=False, help_text='Whether deposit has been paid')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from tenant', null=True)),
                ('landlord_notes', models.TextField(blank=True, help_text='Notes from landlord', null=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Unit the tenant is applying for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.unit')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['landlord', 'status'], name='accounts_te_landlor_994d37_idx'), models.Index(fields=['tenant', 'status'], name='accounts_te_tenant__ba5922_idx')],
            },
        ),
    ]
