# Generated by Django 4.2.7 on 2025-10-28 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_id_document_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('property_created', 'Property Created'), ('property_deleted', 'Property Deleted'), ('unit_created', 'Unit Created'), ('unit_deleted', 'Unit Deleted')], max_length=30)),
                ('subscription_plan', models.CharField(help_text='Plan at the time of action', max_length=20)),
                ('total_properties_after', models.IntegerField(help_text='Total properties after this action')),
                ('total_units_after', models.IntegerField(help_text='Total units after this action')),
                ('upgrade_notification_sent', models.BooleanField(default=False, help_text='Whether upgrade notification was sent')),
                ('limit_reached', models.BooleanField(default=False, help_text='Whether limit was reached with this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='property_unit_tracking', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='accounts.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='accounts.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'action'], name='accounts_pr_landlor_b49632_idx'), models.Index(fields=['landlord', 'created_at'], name='accounts_pr_landlor_5beeac_idx'), models.Index(fields=['limit_reached'], name='accounts_pr_limit_r_618351_idx')],
            },
        ),
    ]
